name: Github Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Content
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Generate Appstream releases
        shell: bash
        run: python ./generate-appstream-releases.py docs/mozillavpn.json > docs/org.mozilla.vpn.releases.xml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
  
  deploy:
    name: Deploy Pages
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment

      - name: Triger flathub updates
        env:
          FLATHUB_TOKEN: ${{ secrets.FLATHUB_TOKEN }}
          FLATHUB_API_URL: https://api.github.com/repos/flathub/org.mozilla.vpn/actions/workflows/update-check.yml/dispatches
        run: |
          curl -sSL -X POST -d '{"ref":"master"}' \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${FLATHUB_TOKEN}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             ${FLATHUB_API_URL}

